name: Compilar APK de Ordia

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Preparar Java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: temurin
          java-version: "21"

      - name: Instalar Gradle 8.13
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
        with:
          gradle-version: "8.13"

      - name: Compilar APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Localizar APK
        run: find . -type f -name "*.apk"

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Ordia-3.0-preview-debug-apks
          path: app/build/outputs/apk/*/debug/*.apk
          if-no-files-found: error
          retention-days: 30
